check-for-permission: false
allow-orangetext: true
enabled-by-default: true
greentext-exceptions:
        - ':'
        - '_'
        - '.'
orangetext-exceptions:
        - ':'
        - '_'
        - '.'
debug: false
check-for-updates: true
